# Generated by Django 4.2.5 on 2023-09-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_alter_authuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('user', 'System User'), ('admin', 'System Admin')], default='user', max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapi.role'),
        ),
    ]
