# Generated by Django 4.2.5 on 2023-09-12 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_role_remove_authuser_is_admin_authuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_role',
            field=models.CharField(choices=[('user', 'System User'), ('admin', 'System Admin'), ('super', 'Super Admin')], default='user', max_length=30),
        ),
    ]
