# Generated by Django 4.2.5 on 2023-09-13 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0008_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='lead',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
